In [2]:
import pandas as pd

df = pd.read_csv('messy_ecommerce.csv')

df.head()

,order_id,customer_name,email,product,category,price,quantity,order_date,shipping_status,country
0,ORD1000,NaN,test@gmail.com,Tablet,NaN,1136.18,2,11/6/2024,Shipped,usa
1,ORD1001,Maria Lopez,example@outlook.com,Phone,ELECTRONICS,168.35,4,1/2/2023,Delivered,USA
2,ORD1002,Timmy Pual,test@gmail.com,Phone,NaN,209.13,3,10/26/2023,Delivered,United States
3,ORD1003,Carlos Ruiz,user@yahoo.com,Keyboard,NaN,1373.69,1,12/2/2023,Canceled,Mexico
4,ORD1004,Amy Tims,example@outlook.com,Monitor,ELECTRONICS,468.47,5,11/17/2023,Shipped,United States

In [8]:
df.isnull().sum()

order_id            54
customer_name      443
email              562
product              0
category           513
price               96
quantity             0
order_date          68
shipping_status      0
country            432
dtype: int64

In [18]:
df['customer_name'] = df['customer_name'].fillna('Unknown')
df['email'] = df['email'].fillna('noemail@gmail.com')
df['category'] = df['category'].fillna('Unknown')  
df['country'] = df['country'].fillna('Unknown') 
df['price'] = df['price'].fillna(df['price'].median())

In [10]:
df.duplicated().sum()

np.int64(91)

In [19]:
df = df.drop_duplicates()

In [22]:
df['country'].unique

<bound method Series.unique of 0                 usa
1                 USA
2       United States
3              Mexico
4       United States
            ...
2040          Unknown
2048              usa
2068              usa
2071           Mexico
2087          Unknown
Name: country, Length: 2009, dtype: str>

In [28]:
df['country'] = df['country'].str.strip().str.lower()

df['country'] = df['country'].replace({
    'usa': 'United States', 
    'united states': 'United States', 
    'mexico' : 'Mexico'
})

In [26]:
df['category'].unique()

<StringArray>
['Unknown', 'ELECTRONICS', 'electronics', 'Electronics']
Length: 4, dtype: str

In [31]:
df['category'] = df['category'].str.strip().str.capitalize()

In [32]:
df['order_date'].unique()

<StringArray>
[ '11/6/2024',   '1/2/2023', '10/26/2023',  '12/2/2023', '11/17/2023',
  '4/16/2024',   '5/5/2023',  '7/29/2025',  '1/15/2025',   '9/2/2023',
 ...
  '1/17/2025', '11/18/2025',  '3/20/2024',  '4/12/2025',  '3/15/2023',
   '2/1/2025',  '2/20/2026',   '3/8/2025',  '9/19/2024',  '5/14/2024']
Length: 943, dtype: str

In [34]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [37]:
df.head()

,order_id,customer_name,email,product,category,price,quantity,order_date,shipping_status,country
0,ORD1000,Unknown,test@gmail.com,Tablet,Unknown,1136.18,2,2024-11-06,Shipped,United States
1,ORD1001,Maria Lopez,example@outlook.com,Phone,Electronics,168.35,4,2023-01-02,Delivered,United States
2,ORD1002,Timmy Pual,test@gmail.com,Phone,Unknown,209.13,3,2023-10-26,Delivered,United States
3,ORD1003,Carlos Ruiz,user@yahoo.com,Keyboard,Unknown,1373.69,1,2023-12-02,Canceled,Mexico
4,ORD1004,Amy Tims,example@outlook.com,Monitor,Electronics,468.47,5,2023-11-17,Shipped,United States

In [38]:
df.to_csv('cleaned_ecommerce.csv', index=False)

In [57]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
username = 'postgres'
password = 'password'
host = 'localhost'
port = '5432'
database = 'ecommerce_project'

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

In [86]:
df.to_sql(
    'cleaned_orders', 
    engine, 
    if_exists='append',
      index=False)

OperationalError: (psycopg2.OperationalError) could not translate host name "S1@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/21/e3q8)